# Generated by Django 2.2.1 on 2019-09-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='log',
            name='title',
            field=models.CharField(default='这是标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.CharField(default='这里写标题', max_length=50),
        ),
    ]
